---
title: "R Notebook"
output: html_notebook
---
# install packages
```{r}
install.packages ("tidyverse", dependencies=TRUE)
install.packages ("ggthemes", dependences=TRUE)
```
# load packages
```{r}
library(tidyverse)
library(ggthemes)

```
# import data
```{r}
exp1=read_csv("exp1.csv")
nrow(exp1)
ncol(exp1)
colnames(exp1)
```
# tidyverse verbs
```{r}
condition_data=exp1%>%
  select(subject, rt, typeoftrial, trialcondition, correct)%>%
  filter(typeoftrial=="picture" &
           trialcondition%in%
           c("Heavy_Normal", "Light_Smashed", "Heavy_Smashed", "Light_Normal"))
means=condition_data%>%
  group_by(trialcondition)%>%
summarise(mean_rt=mean(rt),
          sd_rt=sd(rt),
          mean_acc=mean(correct))
```
# ggplot
```{r}
  library(ggplot2)
  library(ggthemes)
condition_data%>%
  filter(rt<25000)%>%
  ggplot(aes(x=rt))+
  geom_histogram(binwidth=1000,
                 fill="purple", color="black",
                 position="identity")+
  theme_few()+
  xlab("RT (in milliseconds)")+
  ylab("Count")+
  ggtitle("Histogram of RT")
```
# bar graphs
```{r}
means%>%
  ggplot(aes(x=trialcondition, y=mean_rt))+
  geom_bar(stat="identity", fill="pink", color="magenta")+
  theme_fivethirtyeight()+
  xlab("RT(in milliseconds)")+
  ylab("Count")+
  ggtitle("Barplot of RT")
```
# class exercises 
```{r}
df = read_csv("relatedness_exp (1).csv")

```

```{r}
part_df = df%>%
  select(ID, Type, pathlength, RT)%>%
  filter(Type=="related" & pathlength%in%c(1,2))
  

```

# exercise 2
```{r}
mean_all = df%>%
  summarise(mean=mean(RT))
mean_part = part_df%>%summarize (mean=mean(RT))
  mean_ID = df%>%group_by(ID)%>%summarize(mean=mean(RT))
  

```



